services:
  web:
    build: .
    image: movilidadsostenible-yamaha:latest
    container_name: movilidad-web
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      ASPNETCORE_URLS: "http://+:8080;https://+:8443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${HTTPS_CERT_PASSWORD}"
    volumes:
      - type: bind
        source: ${HTTPS_CERT_PATH}
        target: /https
        read_only: true